name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          # Use GITHUB_TOKEN if SEMENTIC_AND_DEPBOT_TOKEN is not available
          GITHUB_TOKEN: ${{ secrets.SEMENTIC_AND_DEPBOT_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
